version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mytestdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcde12345
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app
    restart: always
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/mytestdb
      DB_USERNAME: postgres
      DB_PASSWORD: abcde12345
      JWT_SECRET_KEY: HbDkWm3IraT81GuLLeVqG+mNviOHaRkxDWKatN3SxQ4=
      ADMIN_CODE: seongmingod13
      GOOGLE_API_KEY: AIzaSyCE8NCj2poxVeGzPJNMc8fGu6eeP1dYiE8
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
